##URL FORMAT : jdbc:<TargetDatabase(H2/MYSQL)>:URL OF THE DATABAE: DatabaseName
#spring.datasource.url=jdbc:mysql://localhost:3306/blog_test
#
#spring.datasource.username:root
#spring.datasource.password:Admin@123

#URL FORMAT : jdbc:<TargetDatabase(H2/MYSQL)>:URL OF THE DATABAE: DatabaseName
#spring.datasource.url=jdbc:postgresql://dpg-cksb0c10at9c73c06530-a.oregon-postgres.render.com/database_qspo

spring.datasource.url=jdbc:postgresql://dpg-cl3b3tpnovjs73bfcss0-a/bmd_wax3

spring.datasource.username:bmd_wax3_user
spring.datasource.password:ufl1yPnEOcscCIuTPi5htc3y1FZt5vWl







