spring.application.name=FoodDeliveryApplication

server.servlet.context-path=/food-application

#spring.profiles.active=${ENV:dev}
server.port=${PORT:8081}

app.base-url=${APP_BASE_URL:http://localhost:8081/food-application}

spring.profiles.active=${ENV:dev}

storage.provider=${STORAGE_PROVIDER:supabase}
#${ENV:prod}

#The following Property will log all database statements
spring.jpa.show-sql = true
#The following property will log all database statement in readable format
spring.jpa.properties.hibernate.format_sql=true
#DDL Mode
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

#aws s3 configuration

aws.access.key=${AWS-ACCESS-KEY}
aws.secret.key=${AWS-SECRET-KEY}
aws.region=${AWS-REGION}
aws.s3.bucketname=${AWS_BUCKET:foodies-food}

supabase.url=${SUPABASE_URL:https://sihdsmtwezpvqufqwczy.supabase.co}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaGRzbXR3ZXpwdnF1ZnF3Y3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MzExMjQsImV4cCI6MjA5NDAwNzEyNH0.d04JAxLvuvnocoHVCeQ12mAT3DnaJteEnwHa6Gc9khA}
supabase.bucket=${SUPABASE_BUCKET:food-images}
supabase.region=${SUPABASE_REGION:Asia-Pacific}

jwt.secret.key=${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMTIzNDU2}

# razorpay configuration

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}

# Every 50 seconds
app.scheduler.keep-alive.cron=*/50 * * * * *

# Enable/Disable scheduler
app.scheduler.keep-alive.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always